version: 0.2
CODEBUILD_BUILD_SUCCEEDING: 0
phases:
    install:
        commands:
            - nvm install --lts
            - 'touch .npmignore'
            - 'npm install -g yarn gatsby gatsby-cli'
    pre_build:
        commands:
            - n 16
            - 'yarn install'
    build:
        commands:
        
            - n 16
            - 'gatsby build'

    post_build:
        commands:
            - test "$CODEBUILD_BUILD_SUCCEEDING" = "1"
            - 'yarn run deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/**/*'
        - 'node_modules/**/*'
        - 'public/**/*'
